const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),url=require("url");
const PORT=Number(process.env.PORT)||3000,HOST="0.0.0.0",ROOT=__dirname,PUBLIC=ROOT,DATA_DIR=path.join(ROOT,"data"),DATA=path.join(ROOT,"data","db.json"),UPLOADS=path.join(ROOT,"uploads");
fs.mkdirSync(DATA_DIR,{recursive:true});
fs.mkdirSync(UPLOADS,{recursive:true});
const sessions=new Map();
const seed=()=>({users:[
{id:"u1",role:"customer",name:"Arjun Mehta",email:"owner@demo.com",password:"owner123",phone:"+91 98765 43210",alternatePhone:"+91 98765 43211",address:"Whitefield, Bengaluru",city:"Bengaluru",country:"India",emergencyContact:"Meera Mehta · +91 98765 43212",status:"active",joinedAt:"2026-06-15"},
{id:"u2",role:"guardian",name:"Ravi Kumar",email:"guardian@demo.com",password:"guardian123",phone:"+91 90000 10010",status:"active"},
{id:"u3",role:"admin",name:"Priya Shah",email:"admin@demo.com",password:"admin123",phone:"+91 90000 10011",status:"active"}],
properties:[{id:"p1",ownerId:"u1",name:"Greenwood Residence",address:"Whitefield, Bengaluru",type:"Villa",bedrooms:4,bathrooms:3,area:"2,450 sq ft",year:2020,health:86,baseline:"15 Jun 2026",guardianId:"u2",plan:"Guardian Plus",access:"Owner-approved visit"}],
rooms:[
{id:"r1",propertyId:"p1",name:"Living Room",floor:"Ground",condition:"Good"},
{id:"r2",propertyId:"p1",name:"Kitchen",floor:"Ground",condition:"Good"},
{id:"r3",propertyId:"p1",name:"Master Bedroom",floor:"First",condition:"Good"},
{id:"r4",propertyId:"p1",name:"Bathrooms",floor:"First",condition:"Watch"},
{id:"r5",propertyId:"p1",name:"Exterior / Utility",floor:"Ground",condition:"Good"}],
assets:[
{id:"a1",propertyId:"p1",name:"Daikin Split AC",category:"HVAC",serial:"AC-4438",lastService:"02 Feb 2026",status:"Monitor"},
{id:"a2",propertyId:"p1",name:"Bosch Refrigerator",category:"Appliance",serial:"BR-8831",lastService:"20 Apr 2026",status:"Good"},
{id:"a3",propertyId:"p1",name:"Water Heater",category:"Plumbing",serial:"WH-2209",lastService:"15 Jan 2026",status:"Good"}],
documents:[
{id:"d1",propertyId:"p1",name:"Property Insurance",type:"Insurance",expires:"31 Dec 2026"},
{id:"d2",propertyId:"p1",name:"Appliance Warranty Pack",type:"Warranty",expires:"15 May 2027"},
{id:"d3",propertyId:"p1",name:"Property Inventory",type:"Inventory",expires:"—"}],
visits:[
{id:"v1",propertyId:"p1",guardianId:"u2",date:"2026-09-15",time:"10:30",status:"admin_approved",checklist:24,evidence:2,health:86,adminReviewedAt:"2026-09-15T11:00:00.000Z",adminReviewedBy:"Priya Shah"},
{id:"v2",propertyId:"p1",guardianId:"u2",date:"2026-09-16",time:"10:30",status:"scheduled",checklist:24,evidence:0}],
issues:[{id:"i1",propertyId:"p1",visitId:"v1",room:"Master Bedroom",title:"AC drain moisture",severity:"medium",status:"sent_to_owner",occurrences:3,description:"Similar moisture was documented in 3 of the last 4 inspections."},{id:"i_demo",propertyId:"p1",visitId:"v1",room:"Kitchen",title:"Kitchen sink seepage",severity:"low",status:"owner_approved",occurrences:2,description:"Light seepage observed beneath the sink during two inspections.",reportedBy:"Ravi Kumar",firstDetected:"2026-08-18",lastObserved:"2026-09-15",guardianObservation:"Light seepage observed beneath the sink during two inspections.",adminReview:{status:"approved",reviewedBy:"Priya Shah",reviewedAt:"2026-09-15T10:55:00.000Z",note:"Evidence reviewed; owner approval required before maintenance."},ownerDecision:{status:"owner_approved",decidedBy:"Arjun Mehta",decidedAt:"2026-09-15T12:05:00.000Z",note:"Approved the maintenance next step."},maintenanceStatus:"quote_pending",ai:{summary:"Minor recurring seepage has been recorded twice.",recommendation:"Obtain a plumbing quote and verify the source before replacement.",confidence:"Pattern supported by prior records"}}],
evidence:[],history:[
{id:"h1",propertyId:"p1",date:"2026-09-15",title:"Inspection completed",detail:"24/24 checks · 2 evidence items · GPS verified · Health 86"},
{id:"h2",propertyId:"p1",date:"2026-08-18",title:"AC drain moisture noted",detail:"Owner notified · No repair authorized"},
{id:"h3",propertyId:"p1",date:"2026-07-16",title:"Inspection completed",detail:"No major issues · Health 83"},
{id:"h4",propertyId:"p1",date:"2026-06-15",title:"Baseline refreshed",detail:"Day-0 condition record · Health 81"}],
audit:[{time:"10:31",actor:"Ravi Kumar",action:"GPS check-in verified"},{time:"10:42",actor:"Ravi Kumar",action:"Evidence uploaded"},{time:"10:52",actor:"AI Engine",action:"Recurring moisture pattern identified"},{time:"10:54",actor:"Ravi Kumar",action:"Inspection submitted"}],
vendors:[{id:"ven1",name:"CoolCare HVAC Services",category:"HVAC",contact:"+91 90000 10001",rating:4.8,verified:true},{id:"ven2",name:"AquaFix Home Services",category:"Plumbing",contact:"+91 90000 10002",rating:4.6,verified:true},{id:"ven3",name:"Prime Electricals",category:"Electrical",contact:"+91 90000 10003",rating:4.7,verified:true}],
quotes:[{id:"q1",issueId:"i_demo",vendorId:"ven2",amount:2850,estimateDate:"2026-09-18",status:"pending_owner",notes:"Replace worn trap connector and pressure-test the line."}],
workOrders:[{id:"wo_demo",issueId:"i_demo",quoteId:"q1",vendorId:"ven2",status:"awaiting_owner_approval",scheduledDate:null,scheduledTime:null,beforeEvidence:[],afterEvidence:[],completionNote:""}],
maintenancePlans:[{id:"mp1",propertyId:"p1",assetId:"a1",title:"HVAC preventive service",category:"HVAC",dueDate:"2026-10-02",frequency:"Every 6 months",priority:"medium",status:"upcoming",notes:"Review AC drain path, filter condition and condensate flow. This is a planning reminder, not a diagnosis."},{id:"mp2",propertyId:"p1",assetId:"a3",title:"Water heater service review",category:"Plumbing",dueDate:"2026-10-15",frequency:"Every 9 months",priority:"low",status:"upcoming",notes:"Review service history and visible condition during the next scheduled visit."}],
notifications:[],
financials:[{id:"fin1",propertyId:"p1",type:"subscription",description:"Guardian Plus · September 2026",amount:1499,status:"paid",dueDate:"2026-09-05",paidDate:"2026-09-04"}],
accessRecords:[{id:"ac1",propertyId:"p1",method:"Owner-approved visit",provider:"Property Guardian",status:"active",lastUsed:"2026-09-15 10:30",notes:"Guardian access for scheduled inspections only."}]});
if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(seed(),null,2));
const db=()=>{let d=JSON.parse(fs.readFileSync(DATA));
 d.issues.forEach(i=>{if(i.status==="needs_review")i.status="admin_review"; if(!i.firstDetected)i.firstDetected=i.createdAt||"2026-08-18"; if(!i.lastObserved)i.lastObserved=i.createdAt||"2026-09-15"; if(!i.reportedBy)i.reportedBy="Guardian"; if(!i.guardianObservation)i.guardianObservation=i.description||"Visible condition observed during inspection."; if(!i.adminReview)i.adminReview={status:i.status==="sent_to_owner"?"approved":"pending"}; if(!i.ownerDecision)i.ownerDecision={status:i.status==="sent_to_owner"?"awaiting":i.status};});
 d.visits.forEach(v=>{if(v.status==="completed")v.status="admin_approved"; if(v.status==="admin_review")v.reportStatus="awaiting_admin_review";});
 if(!Array.isArray(d.notifications))d.notifications=[];
 if(!Array.isArray(d.financials))d.financials=[];
 if(!Array.isArray(d.accessRecords))d.accessRecords=[];
 d.users.forEach(x=>{if(!x.status)x.status="active"; if(!x.joinedAt)x.joinedAt="—"; if(x.role==="customer"){if(!x.phone)x.phone="+91 98765 43210";if(!x.alternatePhone)x.alternatePhone="—";if(!x.address)x.address="Whitefield, Bengaluru";if(!x.city)x.city="Bengaluru";if(!x.country)x.country="India";if(!x.emergencyContact)x.emergencyContact="—";}});
 if(!d.financials.length){d.financials=[{id:"fin1",propertyId:"p1",type:"subscription",description:"Guardian Plus · September 2026",amount:1499,status:"paid",dueDate:"2026-09-05",paidDate:"2026-09-04"}]};
 if(!d.accessRecords.length){d.accessRecords=[{id:"ac1",propertyId:"p1",method:"Owner-approved visit",provider:"Property Guardian",status:"active",lastUsed:"2026-09-15 10:30",notes:"Guardian access for scheduled inspections only."}]}; if(!Array.isArray(d.maintenancePlans))d.maintenancePlans=[]; if(!d.maintenancePlans.length){d.maintenancePlans=[{id:"mp1",propertyId:"p1",assetId:"a1",title:"HVAC preventive service",category:"HVAC",dueDate:"2026-10-02",frequency:"Every 6 months",priority:"medium",status:"upcoming",notes:"Review AC drain path, filter condition and condensate flow. Planning reminder only."},{id:"mp2",propertyId:"p1",assetId:"a3",title:"Water heater service review",category:"Plumbing",dueDate:"2026-10-15",frequency:"Every 9 months",priority:"low",status:"upcoming",notes:"Review service history and visible condition during the next scheduled visit."}] ;}
 if(!Array.isArray(d.vendors))d.vendors=[]; if(!Array.isArray(d.quotes))d.quotes=[]; if(!Array.isArray(d.workOrders))d.workOrders=[];
 d.issues.forEach(i=>{if(i.status==="owner_approved"&&i.maintenanceStatus==null)i.maintenanceStatus="ready_for_quote";});
 d.issues.forEach(i=>{if(i.status==="more_info_requested"&&!i.ownerDecision?.notificationCreated){const owner=i.ownerDecision?.decidedBy||"Owner";d.notifications.unshift({id:"n_migrate_"+i.id,recipientRole:"admin",recipientId:"u3",type:"owner_more_info",title:"Owner requested more information",message:`${owner} requested more information for ${i.title}.`,issueId:i.id,propertyId:i.propertyId,createdAt:i.ownerDecision?.decidedAt||now().toISOString(),readAt:null});i.ownerDecision.notificationCreated=true;}});d.issues.forEach(i=>{if(i.status==="sent_to_owner"&&!i.ownerDecision?.releasedNotificationCreated){const prop=d.properties.find(p=>p.id===i.propertyId);d.notifications.unshift({id:"n_release_"+i.id,recipientRole:"customer",recipientId:prop?.ownerId,type:"issue_released",title:"Finding ready for your decision",message:`Admin reviewed ${i.title} at ${prop?.name||"your property"}. Review the finding and decide what happens next.`,issueId:i.id,propertyId:i.propertyId,actionRequired:true,createdAt:i.adminReview?.reviewedAt||now().toISOString(),readAt:null});i.ownerDecision.releasedNotificationCreated=true;}});d.visits.forEach(v=>{if(v.status==="admin_approved"&&!v.releaseNotificationCreated){const prop=d.properties.find(p=>p.id===v.propertyId);d.notifications.unshift({id:"n_visit_"+v.id,recipientRole:"customer",recipientId:prop?.ownerId,type:"inspection_released",title:"Inspection report is ready",message:`Your ${prop?.name||"property"} inspection from ${v.date} is now available.`,visitId:v.id,propertyId:v.propertyId,actionRequired:false,createdAt:v.adminReviewedAt||now().toISOString(),readAt:null});v.releaseNotificationCreated=true;}});
 return d};const save=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));
const now=()=>new Date();const clock=()=>now().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});
function send(res,status,obj,headers={}){res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store",...headers});res.end(JSON.stringify(obj))}
function body(req){return new Promise(resolve=>{let b="";req.on("data",c=>b+=c);req.on("end",()=>{try{resolve(b?JSON.parse(b):{})}catch{resolve({})}})})}
function current(req){let m=(req.headers.cookie||"").match(/sid=([^;]+)/);return m&&sessions.get(decodeURIComponent(m[1]))?.user}
function requireUser(req,res,roles){let u=current(req);if(!u){send(res,401,{error:"login_required"});return null}if(roles&&!roles.includes(u.role)){send(res,403,{error:"forbidden"});return null}return u}
function staticFile(res,p){let rel=p==="/"?"index.html":p.replace(/^\/+/,"");let f=path.resolve(PUBLIC,rel);if(!f.startsWith(path.resolve(PUBLIC))||!fs.existsSync(f)){res.writeHead(404);return res.end("Not found")}let ext=path.extname(f),ct={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json"}[ext]||"application/octet-stream";res.writeHead(200,{"Content-Type":ct});fs.createReadStream(f).pipe(res)}
http.createServer(async(req,res)=>{
 const p=url.parse(req.url).pathname;
 if(p.startsWith("/uploads/")){let f=path.join(UPLOADS,path.basename(p));if(fs.existsSync(f)){res.writeHead(200,{"Content-Type":"image/jpeg","Cache-Control":"no-store"});return fs.createReadStream(f).pipe(res)}return send(res,404,{error:"not_found"})}
 if(p==="/app"||p==="/login"){return staticFile(res,"/app.html")}
 if(p.startsWith("/api/")){
  if(req.method==="POST"&&p==="/api/login"){let b=await body(req),d=db(),u=d.users.find(x=>x.email.toLowerCase()===String(b.email||"").toLowerCase()&&x.password===b.password);if(!u)return send(res,401,{error:"Invalid email or password"});let sid=crypto.randomBytes(32).toString("hex");sessions.set(sid,{user:{id:u.id,role:u.role,name:u.name,email:u.email}});return send(res,200,{user:{id:u.id,role:u.role,name:u.name,email:u.email}},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/`})}
  if(req.method==="POST"&&p==="/api/logout"){let m=(req.headers.cookie||"").match(/sid=([^;]+)/);if(m)sessions.delete(decodeURIComponent(m[1]));return send(res,200,{ok:true},{'Set-Cookie':"sid=; Max-Age=0; Path=/"})}
  if(req.method==="GET"&&p==="/api/me")return send(res,200,{user:current(req)||null});
  let u=requireUser(req,res);if(!u)return;let d=db();
  if(req.method==="GET"&&p==="/api/state")return send(res,200,d);
  if(req.method==="GET"&&p==="/api/dashboard"){let own=d.properties.filter(p=>u.role==="customer"?p.ownerId===u.id:true);return send(res,200,{properties:own,openIssues:d.issues.filter(i=>i.status!=="declined"&&own.some(p=>p.id===i.propertyId)),visits:d.visits.filter(v=>own.some(p=>p.id===v.propertyId)),audit:u.role==="admin"?d.audit:[]})}
  if(req.method==="GET"&&p==="/api/notifications"){let ns=d.notifications.filter(n=>n.recipientRole===u.role&&(n.recipientId==null||n.recipientId===u.id)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return send(res,200,{notifications:ns,unread:ns.filter(n=>!n.readAt).length})}
  if(req.method==="POST"&&p==="/api/notifications/read"){let b=await body(req),n=d.notifications.find(x=>x.id===b.notificationId&&x.recipientRole===u.role&&(x.recipientId==null||x.recipientId===u.id));if(!n)return send(res,404,{error:"notification"});n.readAt=now().toISOString();save(d);return send(res,200,n)}
  if(req.method==="POST"&&p==="/api/notifications/read-all"){let stamp=now().toISOString();d.notifications.filter(n=>n.recipientRole===u.role&&(n.recipientId==null||n.recipientId===u.id)&&!n.readAt).forEach(n=>n.readAt=stamp);save(d);return send(res,200,{ok:true})}
  if(req.method==="POST"&&p==="/api/checkin"){if(u.role!=="guardian")return send(res,403,{error:"guardian_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});v.status="in_progress";v.checkedIn=clock();d.audit.unshift({time:v.checkedIn,actor:u.name,action:"GPS check-in verified",visitId:v.id});save(d);return send(res,200,v)}
  if(req.method==="POST"&&p==="/api/upload"){if(u.role!=="guardian")return send(res,403,{error:"guardian_only"});let b=await body(req);if(!b.data?.startsWith("data:image/"))return send(res,400,{error:"Image required"});let raw=Buffer.from(b.data.split(",")[1],"base64");if(raw.length>8e6)return send(res,400,{error:"Image must be under 8 MB"});let id="ev"+Date.now(),file=id+".jpg";fs.writeFileSync(path.join(UPLOADS,file),raw);let e={id,visitId:b.visitId||"v2",propertyId:b.propertyId||"p1",room:b.room||"General",file:"/uploads/"+file,caption:b.caption||"Inspection evidence",uploadedBy:u.name,createdAt:now().toISOString()};d.evidence.push(e);let v=d.visits.find(x=>x.id===e.visitId);if(v)v.evidence=(v.evidence||0)+1;d.audit.unshift({time:clock(),actor:u.name,action:`Evidence uploaded · ${e.room}`});save(d);return send(res,200,e)}
  if(req.method==="POST"&&p==="/api/complete"){if(u.role!=="guardian")return send(res,403,{error:"guardian_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});if(v.guardianId!==u.id)return send(res,403,{error:"visit_not_assigned"});if(!v.checkedIn)return send(res,409,{error:"checkin_required"});let completed=Array.isArray(v.checklistItems)?v.checklistItems.filter(x=>x.status).length:0;if(completed<24)return send(res,409,{error:"checklist_incomplete",completed});if(!(v.evidence||0))return send(res,409,{error:"evidence_required"});v.status="admin_review";v.reportStatus="awaiting_admin_review";v.submittedAt=now().toISOString();v.checklist=completed;v.checkedOut=clock();v.health=86;d.audit.unshift({time:v.checkedOut,actor:u.name,action:"Inspection submitted",visitId:v.id});d.history.unshift({id:"h"+Date.now(),propertyId:v.propertyId,date:now().toISOString().slice(0,10),title:"Inspection submitted for Admin review",detail:`${completed}/24 checks · ${v.evidence||0} evidence items · GPS verified · Awaiting Admin review`});save(d);return send(res,200,v)}
  if(req.method==="GET"&&p==="/api/report"){if(!["customer","admin"].includes(u.role))return send(res,403,{error:"not_allowed"});let q=new URL(req.url,"http://localhost"),pid=q.searchParams.get("propertyId"),prop=d.properties.find(x=>x.id===pid);if(!prop)return send(res,404,{error:"property"});if(u.role==="customer"&&prop.ownerId!==u.id)return send(res,403,{error:"property_access"});let visits=d.visits.filter(v=>v.propertyId===pid).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),latest=visits[0]||null,ev=latest?d.evidence.filter(e=>e.visitId===latest.id):[],issues=d.issues.filter(i=>i.propertyId===pid),open=issues.filter(i=>!["owner_declined","informational","closed"].includes(i.status)),health=latest?.health??prop.health??100;return send(res,200,{property:prop,latestVisit:latest,evidence:ev,issues:open,health,summary:latest?.status!=="admin_approved"?"Latest inspection is awaiting Admin review before it becomes an owner-facing report.":open.length?`${open.length} active finding${open.length>1?"s":""} require owner review.`:"No active findings were recorded in the latest approved report.",recommendation:open.some(i=>["critical","high"].includes(i.severity))?"Prioritize high-severity findings and obtain a qualified professional assessment.":"Continue scheduled inspections and monitor recurring conditions."})}
  if(req.method==="POST"&&p==="/api/admin/review-issue"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),i=d.issues.find(x=>x.id===b.issueId);if(!i)return send(res,404,{error:"issue"});if(!["admin_review","sent_back"].includes(i.status))return send(res,409,{error:"issue_not_pending_admin_review"});let action=b.action||"send_to_owner";let map={send_to_owner:"sent_to_owner",informational:"informational",send_back:"sent_back"};if(!map[action])return send(res,400,{error:"invalid_action"});i.status=map[action];i.adminReview={status:action==="send_to_owner"?"approved":action,reviewedBy:u.name,reviewedAt:now().toISOString(),note:String(b.note||"")};i.ownerDecision={status:action==="send_to_owner"?"awaiting":action};if(action==="send_to_owner"&&!i.ownerDecision.releasedNotificationCreated){const prop=d.properties.find(p=>p.id===i.propertyId);d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:prop?.ownerId,type:"issue_released",title:"Finding ready for your decision",message:`Admin reviewed ${i.title} at ${prop?.name||"your property"}. Review the finding and decide what happens next.`,issueId:i.id,propertyId:i.propertyId,actionRequired:true,createdAt:now().toISOString(),readAt:null});i.ownerDecision.releasedNotificationCreated=true;}d.audit.unshift({time:clock(),actor:u.name,action:`Admin review · ${action}`,issueId:i.id});save(d);return send(res,200,i)}
  if(req.method==="POST"&&p==="/api/owner/decision"){if(u.role!=="customer")return send(res,403,{error:"customer_only"});let b=await body(req),i=d.issues.find(x=>x.id===b.issueId),prop=i&&d.properties.find(x=>x.id===i.propertyId);if(!i)return send(res,404,{error:"issue"});if(!prop||prop.ownerId!==u.id)return send(res,403,{error:"property_access"});if(i.status!=="sent_to_owner")return send(res,409,{error:"issue_not_ready_for_owner"});let action=b.action||"more_info";if(!["approve","decline","more_info"].includes(action))return send(res,400,{error:"invalid_action"});let status={approve:"owner_approved",decline:"owner_declined",more_info:"more_info_requested"}[action],note=String(b.note||"");i.status=status;i.ownerDecision={status,decidedBy:u.name,decidedAt:now().toISOString(),note};if(action==="more_info"){let nid="n"+Date.now();d.notifications.unshift({id:nid,recipientRole:"admin",recipientId:null,type:"owner_more_info",title:"Owner requested more information",message:`${u.name} requested more information for ${i.title} at ${prop.name}.`,issueId:i.id,propertyId:i.propertyId,createdAt:now().toISOString(),readAt:null});i.ownerDecision.notificationCreated=true;}d.audit.unshift({time:clock(),actor:u.name,action:`Owner decision · ${action}`,issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:action==="more_info"?"Owner requested more information":"Owner decision recorded",detail:action==="more_info"?`${i.title} · Admin notified · ${note||"No note added"}`:`${i.title} · ${status}`});save(d);return send(res,200,i)}
  if(req.method==="POST"&&p==="/api/admin/respond-more-info"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),i=d.issues.find(x=>x.id===b.issueId);if(!i)return send(res,404,{error:"issue"});if(i.status!=="more_info_requested")return send(res,409,{error:"more_info_not_pending"});let note=String(b.note||"").trim();if(!note)return send(res,400,{error:"response_required"});i.adminResponse={status:"sent_to_owner",respondedBy:u.name,respondedAt:now().toISOString(),note};i.ownerDecision={...(i.ownerDecision||{}),status:"awaiting",adminResponseAt:i.adminResponse.respondedAt};i.status="sent_to_owner";const prop=d.properties.find(p=>p.id===i.propertyId);d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:prop?.ownerId,type:"admin_response",title:"Admin responded to your request",message:`Admin added information for ${i.title}. You can continue your decision.`,issueId:i.id,propertyId:i.propertyId,actionRequired:true,createdAt:now().toISOString(),readAt:null});d.notifications.filter(n=>n.issueId===i.id&&n.recipientRole==="admin"&&!n.readAt).forEach(n=>n.readAt=now().toISOString());d.audit.unshift({time:clock(),actor:u.name,action:"Admin responded to owner information request",issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Admin responded to owner information request",detail:`${i.title} · Response recorded · Owner can continue review`});save(d);return send(res,200,i)}
  if(req.method==="POST"&&p==="/api/admin/review-inspection"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});if(v.status!=="admin_review")return send(res,409,{error:"inspection_not_pending_review"});let action=b.action||"approve";if(!["approve","send_back"].includes(action))return send(res,400,{error:"invalid_action"});v.status=action==="approve"?"admin_approved":"sent_back";v.reportStatus=action==="approve"?"owner_visible":"awaiting_guardian_resubmission";v.adminReview={status:action,reviewedBy:u.name,reviewedAt:now().toISOString(),note:String(b.note||"")};const prop=d.properties.find(p=>p.id===v.propertyId);if(action==="approve"&&!v.releaseNotificationCreated){d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:prop?.ownerId,type:"inspection_released",title:"Inspection report is ready",message:`Your ${prop?.name||"property"} inspection from ${v.date} is now available.`,visitId:v.id,propertyId:v.propertyId,actionRequired:false,createdAt:now().toISOString(),readAt:null});v.releaseNotificationCreated=true;}if(action==="send_back"){d.notifications.unshift({id:"n"+Date.now(),recipientRole:"guardian",recipientId:v.guardianId,type:"inspection_correction",title:"Inspection needs corrections",message:`Admin reviewed the ${v.date} inspection and requested corrections before owner release.`,visitId:v.id,propertyId:v.propertyId,actionRequired:true,createdAt:now().toISOString(),readAt:null});}d.audit.unshift({time:clock(),actor:u.name,action:`Inspection review · ${action}`,visitId:v.id});d.history.unshift({id:"h"+Date.now(),propertyId:v.propertyId,date:now().toISOString().slice(0,10),title:action==="approve"?"Inspection approved by Admin":"Inspection sent back to Guardian",detail:action==="approve"?`Report released to owner · ${v.checklist||0}/24 checks · ${v.evidence||0} evidence`:`Admin requested corrections before owner release`});save(d);return send(res,200,v)}
  if(req.method==="GET"&&p==="/api/maintenance"){if(!["admin","customer"].includes(u.role))return send(res,403,{error:"not_allowed"});let q=new URL(req.url,"http://localhost"),pid=q.searchParams.get("propertyId"),props=u.role==="customer"?d.properties.filter(x=>x.ownerId===u.id):d.properties;let allowed=props.map(x=>x.id);if(pid&&!allowed.includes(pid))return send(res,403,{error:"property_access"});let issues=d.issues.filter(i=>allowed.includes(i.propertyId)&&["owner_approved","quote_pending","repair_scheduled","repair_in_progress","completion_review","closed"].includes(i.status));let quotes=d.quotes.filter(qt=>issues.some(i=>i.id===qt.issueId));let workOrders=d.workOrders.filter(w=>issues.some(i=>i.id===w.issueId));return send(res,200,{vendors:d.vendors,issues,quotes,workOrders})}
  if(req.method==="POST"&&p==="/api/admin/request-quote"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),i=d.issues.find(x=>x.id===b.issueId);if(!i)return send(res,404,{error:"issue"});if(i.status!=="owner_approved")return send(res,409,{error:"issue_not_owner_approved"});let vendor=d.vendors.find(v=>v.id===b.vendorId);if(!vendor)return send(res,404,{error:"vendor"});let amount=Math.max(0,Number(b.amount||0));if(!amount)return send(res,400,{error:"amount_required"});let q={id:"q"+Date.now(),issueId:i.id,vendorId:vendor.id,amount,estimateDate:String(b.estimateDate||""),status:"pending_owner",notes:String(b.notes||"")};d.quotes.unshift(q);i.status="quote_pending";i.maintenanceStatus="quote_pending";d.audit.unshift({time:clock(),actor:u.name,action:`Quote requested · ${vendor.name} · ₹${amount}`,issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Maintenance quote requested",detail:`${i.title} · ${vendor.name} · ₹${amount}`});const prop=d.properties.find(p=>p.id===i.propertyId);d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:prop?.ownerId,type:"quote_ready",title:"Maintenance quote ready for approval",message:`A ₹${amount.toLocaleString("en-IN")} quote is ready for ${i.title} at ${prop?.name||"your property"}.`,issueId:i.id,propertyId:i.propertyId,actionRequired:true,createdAt:now().toISOString(),readAt:null});save(d);return send(res,200,q)}
  if(req.method==="POST"&&p==="/api/owner/approve-quote"){if(u.role!=="customer")return send(res,403,{error:"customer_only"});let b=await body(req),q=d.quotes.find(x=>x.id===b.quoteId),i=q&&d.issues.find(x=>x.id===q.issueId),prop=i&&d.properties.find(x=>x.id===i.propertyId);if(!q||!i)return send(res,404,{error:"quote"});if(!prop||prop.ownerId!==u.id)return send(res,403,{error:"property_access"});if(q.status!=="pending_owner")return send(res,409,{error:"quote_not_pending"});q.status="approved";q.ownerApprovedBy=u.name;q.ownerApprovedAt=now().toISOString();q.ownerNote=String(b.note||"");i.status="repair_scheduled";i.maintenanceStatus="repair_scheduled";let wo=d.workOrders.find(x=>x.quoteId===q.id);if(wo){wo.status="scheduled";wo.scheduledDate=String(b.scheduledDate||"");wo.scheduledTime=String(b.scheduledTime||"");}else{wo={id:"wo"+Date.now(),issueId:i.id,quoteId:q.id,vendorId:q.vendorId,status:"scheduled",scheduledDate:String(b.scheduledDate||""),scheduledTime:String(b.scheduledTime||""),beforeEvidence:[],afterEvidence:[],completionNote:""};d.workOrders.unshift(wo);}d.audit.unshift({time:clock(),actor:u.name,action:`Quote approved · ₹${q.amount}`,issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Maintenance quote approved",detail:`${i.title} · ₹${q.amount} · Repair scheduling started`});d.notifications.unshift({id:"n"+Date.now(),recipientRole:"admin",recipientId:null,type:"quote_approved",title:"Owner approved maintenance quote",message:`${u.name} approved the ₹${q.amount.toLocaleString("en-IN")} quote for ${i.title}. Schedule the repair.`,issueId:i.id,propertyId:i.propertyId,actionRequired:true,createdAt:now().toISOString(),readAt:null});save(d);return send(res,200,{quote:q,workOrder:wo,issue:i})}
  if(req.method==="POST"&&p==="/api/admin/schedule-repair"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),wo=d.workOrders.find(x=>x.id===b.workOrderId),i=wo&&d.issues.find(x=>x.id===wo.issueId);if(!wo||!i)return send(res,404,{error:"work_order"});wo.status="scheduled";wo.scheduledDate=String(b.date||wo.scheduledDate||"");wo.scheduledTime=String(b.time||wo.scheduledTime||"");i.status="repair_scheduled";i.maintenanceStatus="repair_scheduled";d.audit.unshift({time:clock(),actor:u.name,action:`Repair scheduled · ${wo.scheduledDate} ${wo.scheduledTime}`,issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Repair scheduled",detail:`${i.title} · ${wo.scheduledDate} ${wo.scheduledTime}`});save(d);return send(res,200,wo)}
  if(req.method==="POST"&&p==="/api/admin/start-repair"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),wo=d.workOrders.find(x=>x.id===b.workOrderId),i=wo&&d.issues.find(x=>x.id===wo.issueId);if(!wo||!i)return send(res,404,{error:"work_order"});wo.status="in_progress";i.status="repair_in_progress";i.maintenanceStatus="repair_in_progress";d.audit.unshift({time:clock(),actor:u.name,action:"Repair started",issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Repair in progress",detail:i.title});save(d);return send(res,200,wo)}
  if(req.method==="POST"&&p==="/api/admin/repair-evidence"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),wo=d.workOrders.find(x=>x.id===b.workOrderId);if(!wo)return send(res,404,{error:"work_order"});if(!["scheduled","in_progress","completion_review"].includes(wo.status))return send(res,409,{error:"evidence_not_allowed"});if(!["before","after"].includes(b.phase))return send(res,400,{error:"invalid_phase"});if(!b.data?.startsWith("data:image/"))return send(res,400,{error:"Image required"});let raw=Buffer.from(b.data.split(",")[1],"base64");if(raw.length>8e6)return send(res,400,{error:"Image must be under 8 MB"});let id="rev"+Date.now(),file=id+".jpg";fs.writeFileSync(path.join(UPLOADS,file),raw);let item={id,file:"/uploads/"+file,caption:String(b.caption||`${b.phase} repair evidence`),uploadedBy:u.name,createdAt:now().toISOString()};(b.phase==="before"?(wo.beforeEvidence||(wo.beforeEvidence=[])):(wo.afterEvidence||(wo.afterEvidence=[]))).push(item);d.audit.unshift({time:clock(),actor:u.name,action:`Repair ${b.phase} evidence uploaded`,workOrderId:wo.id});save(d);return send(res,200,item)}
  if(req.method==="POST"&&p==="/api/admin/complete-repair"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),wo=d.workOrders.find(x=>x.id===b.workOrderId),i=wo&&d.issues.find(x=>x.id===wo.issueId);if(!wo||!i)return send(res,404,{error:"work_order"});wo.status="completion_review";wo.completionNote=String(b.note||"");i.status="completion_review";i.maintenanceStatus="completion_review";d.audit.unshift({time:clock(),actor:u.name,action:"Repair submitted for completion review",issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Repair awaiting completion verification",detail:`${i.title} · Before/after evidence review required`});save(d);return send(res,200,wo)}
  if(req.method==="POST"&&p==="/api/admin/verify-repair"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),wo=d.workOrders.find(x=>x.id===b.workOrderId),i=wo&&d.issues.find(x=>x.id===wo.issueId),prop=i&&d.properties.find(x=>x.id===i.propertyId);if(!wo||!i)return send(res,404,{error:"work_order"});let approved=b.approved!==false;if(!approved){wo.status="in_progress";i.status="repair_in_progress";i.maintenanceStatus="repair_in_progress";wo.completionNote=String(b.note||"");save(d);return send(res,200,wo)}wo.status="completed";i.status="closed";i.maintenanceStatus="closed";wo.verifiedBy=u.name;wo.verifiedAt=now().toISOString();wo.completionNote=String(b.note||wo.completionNote||"");d.audit.unshift({time:clock(),actor:u.name,action:"Repair verified and issue closed",issueId:i.id});d.history.unshift({id:"h"+Date.now(),propertyId:i.propertyId,date:now().toISOString().slice(0,10),title:"Repair verified & issue closed",detail:`${i.title} · Completion verified by Admin`});d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:prop?.ownerId,type:"repair_completed",title:"Maintenance completed",message:`Admin verified the repair for ${i.title} at ${prop?.name||"your property"}.`,issueId:i.id,propertyId:i.propertyId,actionRequired:false,createdAt:now().toISOString(),readAt:null});save(d);return send(res,200,wo)}
  if(req.method==="POST"&&p==="/api/approve"){if(u.role!=="customer")return send(res,403,{error:"customer_only"});let b=await body(req);return send(res,200,{legacy:true})}
  if(req.method==="POST"&&p==="/api/create-issue"){if(u.role!=="guardian")return send(res,403,{error:"guardian_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});if(v.guardianId!==u.id)return send(res,403,{error:"visit_not_assigned"});let title=String(b.title||"").trim(),severity=["low","medium","high","critical"].includes(b.severity)?b.severity:"medium",description=String(b.description||"").trim();if(!title)return send(res,400,{error:"issue_title_required"});if((severity==="high"||severity==="critical")&&!description)return send(res,400,{error:"description_required_for_priority_issue"});let id="i"+Date.now();let prior=d.issues.filter(i=>i.propertyId===v.propertyId&&i.title.toLowerCase()===title.toLowerCase());let issue={id,propertyId:v.propertyId,visitId:v.id,room:b.room||"General",title,severity,status:"admin_review",occurrences:prior.length+1,description:description||"Reported during inspection.",createdAt:now().toISOString(),reportedBy:u.name,firstDetected:prior[0]?.firstDetected||now().toISOString(),lastObserved:now().toISOString(),guardianObservation:description||"Reported during inspection.",adminReview:{status:"pending"},ownerDecision:{status:"not_released"},ai:{summary:"Pattern reviewed from available local inspection history.",recommendation:severity==="critical"||severity==="high"?"Prioritize owner review and obtain a qualified professional assessment.":"Monitor the condition and consider professional inspection if it recurs.",confidence:prior.length?"Pattern supported by prior matching records":"Initial observation"}};d.issues.unshift(issue);d.audit.unshift({time:clock(),actor:u.name,action:`Issue reported · ${title}`,issueId:id,visitId:v.id});d.history.unshift({id:"h"+Date.now(),propertyId:v.propertyId,date:now().toISOString().slice(0,10),title:"Issue reported",detail:`${severity.toUpperCase()} · ${title} · ${v.id}`});save(d);return send(res,200,issue)}
  if(req.method==="POST"&&p==="/api/checklist"){if(u.role!=="guardian")return send(res,403,{error:"guardian_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});if(v.guardianId!==u.id)return send(res,403,{error:"visit_not_assigned"});
const checklistLabels={entry:"Entry / doors / locks",living:"Living room / walls / windows",kitchen:"Kitchen / sink / appliances",bed1:"Bedroom 1 / windows / surfaces",bed2:"Bedroom 2 / windows / surfaces",bed3:"Bedroom 3 / windows / surfaces",bed4:"Bedroom 4 / windows / surfaces",bath1:"Bathroom 1 / leaks / fixtures",bath2:"Bathroom 2 / leaks / fixtures",bath3:"Bathroom 3 / leaks / fixtures",water:"Water supply / pressure / visible leaks",hvac:"HVAC / AC / drain condition",electrical:"Electrical panels / visible hazards",lights:"Lights / switches / sockets",plumbing:"Visible plumbing condition",appliances:"Major appliances / visible condition",ceilings:"Ceilings / dampness / stains",floors:"Floors / visible damage",walls:"Walls / cracks / moisture signs",exterior:"Exterior / gates / drainage",utility:"Utility area / pumps / tanks",security:"Security devices / access points",inventory:"Inventory / valuables / obvious changes",general:"General condition / unusual observations"};
const items=Array.isArray(b.items)?b.items.slice(0,24).map(x=>({id:String(x.id),status:["ok","attention","na"].includes(x.status)?x.status:"ok",note:String(x.note||"").trim()})):[];
const bad=items.find(x=>x.status==="attention"&&!x.note);if(bad)return send(res,400,{error:`attention_note_required:${checklistLabels[bad.id]||bad.id}`});
v.checklistItems=items;v.checklist=items.filter(x=>x.status==="ok"||x.status==="attention").length;
// Every Attention flag becomes a visible, individually reviewable finding unless the Guardian already created an issue for the same visit/checklist item.
for(const item of items.filter(x=>x.status==="attention")){
 const existing=d.issues.find(i=>i.visitId===v.id&&i.checklistItemId===item.id);
 const roomName=(d.rooms.find(r=>r.propertyId===v.propertyId&&new RegExp((item.id||"").replace(/[0-9]/g,""),'i').test(r.name))?.name)||((item.id||"").startsWith("kitchen")?"Kitchen":(item.id||"").startsWith("bath")?"Bathroom":"General");
 if(existing){existing.guardianObservation=item.note;existing.description=item.note;existing.lastObserved=now().toISOString();}
 else {const title=(item.id==="kitchen"&&/leak|seep|water|drip/i.test(item.note))?"Kitchen sink leakage / seepage":`${checklistLabels[item.id]||item.id} requires attention`;const prior=d.issues.filter(i=>i.propertyId===v.propertyId&&i.title.toLowerCase()===title.toLowerCase());const issue={id:"i"+Date.now()+Math.random().toString(16).slice(2,6),propertyId:v.propertyId,visitId:v.id,checklistItemId:item.id,room:roomName,title,severity:/leak|seep|water|electrical|security|hazard/i.test(item.note)?"high":"medium",status:"admin_review",occurrences:prior.length+1,description:item.note,createdAt:now().toISOString(),reportedBy:u.name,firstDetected:prior[0]?.firstDetected||now().toISOString(),lastObserved:now().toISOString(),guardianObservation:item.note,adminReview:{status:"pending"},ownerDecision:{status:"not_released"},ai:{summary:"Finding surfaced from a Guardian Attention flag and observation.",recommendation:"Review the evidence and observation before deciding whether owner action is needed.",confidence:prior.length?"Pattern supported by prior matching records":"Initial observation"}};d.issues.unshift(issue);d.audit.unshift({time:clock(),actor:u.name,action:`Attention flag converted to finding · ${title}`,issueId:issue.id,visitId:v.id});d.history.unshift({id:"h"+Date.now()+Math.random().toString(16).slice(2,5),propertyId:v.propertyId,date:now().toISOString().slice(0,10),title:"Finding reported",detail:`${issue.severity.toUpperCase()} · ${title} · ${issue.room}`});}
}
d.audit.unshift({time:clock(),actor:u.name,action:`Checklist saved · ${v.checklist}/24`,visitId:v.id});save(d);return send(res,200,v)}
  if(req.method==="GET"&&p==="/api/maintenance-plans"){if(!["admin","customer"].includes(u.role))return send(res,403,{error:"not_allowed"});let q=new URL(req.url,"http://localhost"),pid=q.searchParams.get("propertyId");let plans=d.maintenancePlans.filter(x=>!pid||x.propertyId===pid);if(u.role==="customer")plans=plans.filter(x=>d.properties.some(p=>p.id===x.propertyId&&p.ownerId===u.id));return send(res,200,{plans})}
  if(req.method==="POST"&&p==="/api/admin/create-maintenance-plan"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),prop=d.properties.find(x=>x.id===b.propertyId),asset=b.assetId?d.assets.find(x=>x.id===b.assetId):null;if(!prop)return send(res,404,{error:"property"});let title=String(b.title||"").trim(),dueDate=String(b.dueDate||"").trim();if(!title||!dueDate)return send(res,400,{error:"title_and_due_date_required"});let plan={id:"mp"+Date.now(),propertyId:prop.id,assetId:asset?.id||null,title,category:String(b.category||asset?.category||"General"),dueDate,frequency:String(b.frequency||"One-time"),priority:String(b.priority||"medium"),status:"upcoming",notes:String(b.notes||"")};d.maintenancePlans.unshift(plan);d.audit.unshift({time:clock(),actor:u.name,action:`Preventive maintenance plan created · ${plan.title}`,propertyId:prop.id});d.history.unshift({id:"h"+Date.now(),propertyId:prop.id,date:now().toISOString().slice(0,10),title:"Preventive maintenance planned",detail:`${plan.title} · Due ${plan.dueDate}`});const owner=prop.ownerId;d.notifications.unshift({id:"n"+Date.now(),recipientRole:"customer",recipientId:owner,type:"maintenance_plan",title:"Preventive maintenance planned",message:`${plan.title} is planned for ${prop.name}, due ${plan.dueDate}.`,propertyId:prop.id,actionRequired:false,createdAt:now().toISOString(),readAt:null});save(d);return send(res,200,plan)}
  if(req.method==="POST"&&p==="/api/admin/complete-maintenance-plan"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),plan=d.maintenancePlans.find(x=>x.id===b.planId);if(!plan)return send(res,404,{error:"plan"});plan.status="completed";plan.completedAt=now().toISOString();plan.completionNote=String(b.note||"");d.audit.unshift({time:clock(),actor:u.name,action:`Preventive maintenance completed · ${plan.title}`,propertyId:plan.propertyId});d.history.unshift({id:"h"+Date.now(),propertyId:plan.propertyId,date:now().toISOString().slice(0,10),title:"Preventive maintenance completed",detail:`${plan.title} · ${plan.completionNote||"Completion recorded"}`});save(d);return send(res,200,plan)}
  if(req.method==="GET"&&p==="/api/admin/customers"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let customers=d.users.filter(x=>x.role==="customer").map(c=>({...c,properties:d.properties.filter(p=>p.ownerId===c.id)}));return send(res,200,{customers})}
  if(req.method==="GET"&&p==="/api/admin/crm"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});return send(res,200,{customers:d.users.filter(x=>x.role==="customer"),guardians:d.users.filter(x=>x.role==="guardian"),properties:d.properties,visits:d.visits,documents:d.documents,financials:d.financials,accessRecords:d.accessRecords})}
  if(req.method==="POST"&&p==="/api/admin/update-user"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),x=d.users.find(z=>z.id===b.userId);if(!x)return send(res,404,{error:"user"});for(const k of ["name","email","phone","alternatePhone","address","city","country","emergencyContact","status"]){if(b[k]!==undefined)x[k]=String(b[k])}d.audit.unshift({time:clock(),actor:u.name,action:`User profile updated · ${x.name}`,userId:x.id});save(d);return send(res,200,x)}
  if(req.method==="POST"&&p==="/api/admin/update-property"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),x=d.properties.find(z=>z.id===b.propertyId);if(!x)return send(res,404,{error:"property"});for(const k of ["name","address","type","area","plan","access","baseline"]){if(b[k]!==undefined)x[k]=String(b[k])}for(const k of ["bedrooms","bathrooms","year"]){if(b[k]!==undefined)x[k]=Number(b[k])||0}if(b.ownerId!==undefined&&d.users.some(z=>z.id===b.ownerId&&z.role==="customer"))x.ownerId=b.ownerId;if(b.guardianId!==undefined&&d.users.some(z=>z.id===b.guardianId&&z.role==="guardian"))x.guardianId=b.guardianId;d.audit.unshift({time:clock(),actor:u.name,action:`Property CRM updated · ${x.name}`,propertyId:x.id});save(d);return send(res,200,x)}
  if(req.method==="POST"&&p==="/api/admin/create-visit"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),prop=d.properties.find(x=>x.id===b.propertyId);if(!prop)return send(res,404,{error:"property"});let guardian=d.users.find(x=>x.id===(b.guardianId||prop.guardianId)&&x.role==="guardian");if(!guardian)return send(res,404,{error:"guardian"});if(!b.date||!b.time)return send(res,400,{error:"date_and_time_required"});let v={id:"v"+Date.now(),propertyId:prop.id,guardianId:guardian.id,date:String(b.date),time:String(b.time),status:"scheduled",checklist:24,evidence:0};d.visits.push(v);d.audit.unshift({time:clock(),actor:u.name,action:`Visit scheduled · ${prop.name} · ${v.date} ${v.time}`,visitId:v.id});d.history.unshift({id:"h"+Date.now(),propertyId:prop.id,date:now().toISOString().slice(0,10),title:"Inspection scheduled",detail:`${v.date} ${v.time} · ${guardian.name}`});d.notifications.unshift({id:"n"+Date.now(),recipientRole:"guardian",recipientId:guardian.id,type:"visit_scheduled",title:"New inspection assigned",message:`${prop.name} · ${v.date} at ${v.time}.`,visitId:v.id,propertyId:prop.id,actionRequired:true,createdAt:now().toISOString(),readAt:null});save(d);return send(res,200,v)}
  if(req.method==="POST"&&p==="/api/admin/update-visit"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});for(const k of ["date","time","status"]){if(b[k]!==undefined)v[k]=String(b[k])}if(b.guardianId&&d.users.some(x=>x.id===b.guardianId&&x.role==="guardian"))v.guardianId=b.guardianId;d.audit.unshift({time:clock(),actor:u.name,action:`Visit schedule updated · ${v.date} ${v.time}`,visitId:v.id});save(d);return send(res,200,v)}
  if(req.method==="POST"&&p==="/api/admin/add-document"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),prop=d.properties.find(x=>x.id===b.propertyId);if(!prop)return send(res,404,{error:"property"});let doc={id:"d"+Date.now(),propertyId:prop.id,name:String(b.name||"Document"),type:String(b.type||"Other"),expires:String(b.expires||"—"),reference:String(b.reference||"")};d.documents.push(doc);d.audit.unshift({time:clock(),actor:u.name,action:`Property document added · ${doc.name}`,propertyId:prop.id});save(d);return send(res,200,doc)}
  if(req.method==="POST"&&p==="/api/admin/add-financial"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),prop=d.properties.find(x=>x.id===b.propertyId);if(!prop)return send(res,404,{error:"property"});let item={id:"fin"+Date.now(),propertyId:prop.id,type:String(b.type||"charge"),description:String(b.description||""),amount:Number(b.amount||0),status:String(b.status||"pending"),dueDate:String(b.dueDate||""),paidDate:String(b.paidDate||"")};d.financials.push(item);d.audit.unshift({time:clock(),actor:u.name,action:`Financial record added · ₹${item.amount}`,propertyId:prop.id});save(d);return send(res,200,item)}
  if(req.method==="POST"&&p==="/api/admin/update-access"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),prop=d.properties.find(x=>x.id===b.propertyId);if(!prop)return send(res,404,{error:"property"});let x=b.accessId?d.accessRecords.find(z=>z.id===b.accessId):null;if(!x){x={id:"ac"+Date.now(),propertyId:prop.id,method:"Owner-approved visit",provider:"Property Guardian",status:"active",lastUsed:"—",notes:""};d.accessRecords.push(x)}for(const k of ["method","provider","status","lastUsed","notes"]){if(b[k]!==undefined)x[k]=String(b[k])}d.audit.unshift({time:clock(),actor:u.name,action:`Access record updated · ${prop.name}`,propertyId:prop.id});save(d);return send(res,200,x)}
  if(req.method==="POST"&&p==="/api/admin/set-sla"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),i=d.issues.find(x=>x.id===b.issueId);if(!i)return send(res,404,{error:"issue"});i.sla={dueAt:String(b.dueAt||""),priority:String(b.priority||i.severity||"medium"),escalation:String(b.escalation||"Admin follow-up")};d.audit.unshift({time:clock(),actor:u.name,action:`Issue SLA updated · ${i.title}`,issueId:i.id});save(d);return send(res,200,i)}
  if(req.method==="POST"&&p==="/api/admin/override-workflow"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req);if(b.issueId){let i=d.issues.find(x=>x.id===b.issueId);if(!i)return send(res,404,{error:"issue"});i.status=String(b.status||i.status);i.adminOverride={by:u.name,at:now().toISOString(),note:String(b.note||"")};d.audit.unshift({time:clock(),actor:u.name,action:`Admin workflow override · ${i.title} → ${i.status}`,issueId:i.id});save(d);return send(res,200,i)}if(b.visitId){let v=d.visits.find(x=>x.id===b.visitId);if(!v)return send(res,404,{error:"visit"});v.status=String(b.status||v.status);v.adminOverride={by:u.name,at:now().toISOString(),note:String(b.note||"")};d.audit.unshift({time:clock(),actor:u.name,action:`Admin visit override · ${v.id} → ${v.status}`,visitId:v.id});save(d);return send(res,200,v)}return send(res,400,{error:"issue_or_visit_required"})}
  if(req.method==="GET"&&p==="/api/admin/report"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let q=new URL(req.url,"http://localhost"),pid=q.searchParams.get("propertyId"),prop=d.properties.find(x=>x.id===pid);if(!prop)return send(res,404,{error:"property"});let owner=d.users.find(x=>x.id===prop.ownerId),guardian=d.users.find(x=>x.id===prop.guardianId),visits=d.visits.filter(v=>v.propertyId===pid).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),issues=d.issues.filter(i=>i.propertyId===pid),fin=d.financials.filter(f=>f.propertyId===pid);return send(res,200,{property:prop,owner,guardian,visits,issues,documents:d.documents.filter(x=>x.propertyId===pid),assets:d.assets.filter(x=>x.propertyId===pid),financials:fin,access:d.accessRecords.filter(x=>x.propertyId===pid),history:d.history.filter(x=>x.propertyId===pid).slice(0,20)})}
  if(req.method==="POST"&&p==="/api/admin/create-property-onboarding"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req);let customer=null,temporaryPassword=null;
    if(b.customerId){customer=d.users.find(x=>x.id===b.customerId&&x.role==="customer");if(!customer)return send(res,404,{error:"customer"});}
    else{let email=String(b.customerEmail||"").trim().toLowerCase();let name=String(b.customerName||"").trim();if(!name||!email)return send(res,400,{error:"customer_name_and_email_required"});if(d.users.some(x=>x.email.toLowerCase()===email))return send(res,409,{error:"customer_email_already_exists"});temporaryPassword=String(b.password||"").trim()||("PG@"+crypto.randomBytes(5).toString("hex"));customer={id:"u"+Date.now(),role:"customer",name,email,password:temporaryPassword,phone:String(b.phone||""),alternatePhone:String(b.alternatePhone||""),address:String(b.customerAddress||""),city:String(b.city||""),country:String(b.country||"India"),emergencyContact:String(b.emergencyContact||""),status:"active",joinedAt:now().toISOString().slice(0,10)};d.users.push(customer)}
    let name=String(b.propertyName||"").trim(),address=String(b.address||"").trim();if(!name||!address)return send(res,400,{error:"property_name_and_address_required"});if(d.properties.some(x=>x.name.toLowerCase()===name.toLowerCase()&&x.address.toLowerCase()===address.toLowerCase()))return send(res,409,{error:"property_already_exists"});
    let guardian=d.users.find(x=>x.id===b.guardianId&&x.role==="guardian");if(!guardian)return send(res,404,{error:"guardian"});let id="p"+Date.now();let prop={id,ownerId:customer.id,name,address,type:String(b.type||"Apartment"),bedrooms:+b.bedrooms||0,bathrooms:+b.bathrooms||0,area:String(b.area||"—"),year:+b.year||0,health:100,baseline:String(b.baseline||"Not set"),guardianId:guardian.id,plan:String(b.plan||"Guardian Essential"),access:String(b.access||"Owner-approved visit")};d.properties.push(prop);
    let roomNames=String(b.rooms||"Living Room, Kitchen, Master Bedroom, Bathrooms, Exterior / Utility").split(",").map(x=>x.trim()).filter(Boolean);roomNames.forEach((rn,idx)=>d.rooms.push({id:"r"+Date.now()+idx,propertyId:id,name:rn,floor:idx>1?"First":"Ground",condition:"Good"}));
    let visit=null;if(b.scheduleFirst){if(!b.date||!b.time)return send(res,400,{error:"first_visit_date_and_time_required"});visit={id:"v"+Date.now(),propertyId:id,guardianId:guardian.id,date:String(b.date),time:String(b.time),status:"scheduled",checklist:24,evidence:0,frequency:String(b.frequency||"One-time")};d.visits.push(visit);d.notifications.unshift({id:"n"+Date.now(),recipientRole:"guardian",recipientId:guardian.id,type:"visit_scheduled",title:"New inspection assigned",message:`${prop.name} · ${visit.date} at ${visit.time}.`,visitId:visit.id,propertyId:id,actionRequired:true,createdAt:now().toISOString(),readAt:null})}
    d.history.unshift({id:"h"+Date.now(),propertyId:id,date:now().toISOString().slice(0,10),title:"Property onboarding completed",detail:`Customer ${customer.name} · Guardian ${guardian.name}${visit?` · First visit ${visit.date} ${visit.time}`:""}`});d.audit.unshift({time:clock(),actor:u.name,action:`Property onboarding completed · ${prop.name}`,propertyId:id,userId:customer.id,guardianId:guardian.id,visitId:visit?.id||null});save(d);return send(res,200,{property:prop,customer,guardian,visit,temporaryPassword});}
  if(req.method==="POST"&&p==="/api/add-property"){if(u.role!=="admin")return send(res,403,{error:"admin_only"});let b=await body(req),id="p"+Date.now();let prop={id,ownerId:"u1",name:b.name,address:b.address,type:b.type||"Apartment",bedrooms:+b.bedrooms||3,bathrooms:+b.bathrooms||2,area:b.area||"—",year:+b.year||now().getFullYear(),health:100,baseline:"Not set",guardianId:"u2",plan:"Guardian Essential",access:"Owner-approved visit"};d.properties.push(prop);d.history.unshift({id:"h"+Date.now(),propertyId:id,date:now().toISOString().slice(0,10),title:"Property Passport created",detail:"Property added by operations"});d.audit.unshift({time:clock(),actor:u.name,action:"Property created",propertyId:id});save(d);return send(res,200,prop)}
  if(req.method==="POST"&&p==="/api/asset/service"){if(!["admin","customer"].includes(u.role))return send(res,403,{error:"not_allowed"});let b=await body(req),a=d.assets.find(x=>x.id===b.assetId),prop=a&&d.properties.find(x=>x.id===a.propertyId);if(!a)return send(res,404,{error:"asset"});if(u.role==="customer"&&(!prop||prop.ownerId!==u.id))return send(res,403,{error:"property_access"});let stamp=now().toISOString();a.lastService=stamp.slice(0,10);a.status="Good";a.lastServiceNote=String(b.note||"");d.audit.unshift({time:clock(),actor:u.name,action:`Asset service recorded · ${a.name}`,propertyId:a.propertyId,assetId:a.id});d.history.unshift({id:"h"+Date.now(),propertyId:a.propertyId,date:stamp.slice(0,10),title:"Asset service recorded",detail:`${a.name} · ${a.category} · Service completed`});save(d);return send(res,200,a)}
  if(req.method==="POST"&&p==="/api/add-asset"){if(!["admin","customer"].includes(u.role))return send(res,403,{error:"not_allowed"});let b=await body(req),id="a"+Date.now();d.assets.push({id,propertyId:b.propertyId,name:b.name,category:b.category||"Other",serial:b.serial||"—",lastService:b.lastService||"Not recorded",status:"Good"});d.audit.unshift({time:clock(),actor:u.name,action:"Asset added",propertyId:b.propertyId});save(d);return send(res,200,{ok:true})}
  return send(res,404,{error:"api_not_found"});
 }
 staticFile(res,p);
}).listen(PORT,HOST,()=>console.log(`Property Guardian demo running on ${HOST}:${PORT}`));